name: Deploy auth

on:
  push:
    branches:
      - auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Update code and inject environment variables
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Inject environment variables
            export ALGORITHM="${{ secrets.ALGORITHM }}"
            export DB_URI="${{ secrets.DB_URI }}"
            export EMAILPASSWORD="${{ secrets.EMAILPASSWORD }}"
            export SECRET_KEY="${{ secrets.SECRET_KEY }}"

            echo "Current directory: $(pwd)"
            cd OnboardingAI/auth-service
            echo "Installing npm packages..."
            npm install

            echo "Starting the Express server..."
            node server.js
            echo "Express server started."
          EOF

      - name: Install libraries and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Installing npm packages..."
            cd OnboardingAI/auth-service
            git checkout auth
            npm install

            echo "Starting the Express server..."
            node server.js
            echo "Express server started."
          EOF

